### ISSUE TITLE
Неактуальная ссылка

### ISSUE THREAD

**Issue by Dan-Crane** [ikherty/droneDOCS#30]
Привет. Спасибо за проект:)

Не удается найти чат:
https://github.com/ikherty/droneDOCS/blob/72d28422302cdf1dd67309754c26d98441ff532c/docs/community/chats.md?plain=1#L116

**Comment by ikherty** [comment]
Спасибо:) 0ee2203f1ca82cc2aab35552c17b60ee5f26589e
