### ISSUE TITLE
Update page <title>. Add heading to page

### ISSUE THREAD

**Issue by Suput** [ikherty/droneDOCS#34]
1. На странице про [Настройки - Рейты](https://propwashservice.ru/settings/rates.html) отсутствует заголовок.
Везде: выбираю статью из оглавления - вижу заголовок статьи и саму статью.
Здесь: выбираю статью из оглавления - вижу сразу текст.
На скриншоте красным - сразу идёт текст, заголовка нет.
![image](https://user-images.githubusercontent.com/40500378/224940074-30f63f26-4aba-4b85-95c1-bb8ade0f2646.png)

2. А ещё на странице [Настройки - Рейты](https://propwashservice.ru/settings/rates.html) нужно добавить тег `<title>` в html `разметку`. На скриншоте зелёным - пример, когда `<title>` указан. На скриншоте красным - чтобы не соврать
![image](https://user-images.githubusercontent.com/40500378/224939848-27d458ed-50aa-44f4-a8a9-8fd1b575b485.png)

**Comment by ikherty** [comment]
это полезное замечание, спасибо, поправила
