### ISSUE TITLE
Дописать про mode 1-4 в статье про аппаратуры

### ISSUE THREAD

**Issue by ikherty** [ikherty/droneDOCS#36]

**Comment by Suput** [comment]
В Инете пишут: "если не знаете с чего начать - берите mode 2"

В принципе - описать что такое mode 1-4 можно (где у них там газ, наклоны, по каким осям)

Но как бонус я бы добавил "откуда эти моды пошли". Левша правша? Тогда почему модов 4?

Upd сразу:
Поискал ещё инфы. Таких примеров мало, но существуют люди (левши, например), кому **УДОБНЕЕ** управлять Mode 1, чем Mode 2
Почему я выделил слово "удобнее"? Потому что, оказывается, так сложилось исторически. Тут уже надо копаться тщательнее

Вырезки из Инета:
- "мода 2 соответствует классическому самолетному управлению .... зато на 3-й, говорят, висеть удобнее". [Надо листать комменты вниз](https://rcopen.com/forum/f4/topic40414/30)
- "Mode-1 для салометов с одними рулями, а Mode-2 для елеронных моделей.". [Надо листать комменты вниз](https://rcopen.com/forum/f4/topic40414/30)
- "3-я и 4- это как раз для левшей восновном заточены - с газом на правой ручке". [Надо листать комменты вниз](https://rcopen.com/forum/f4/topic40414/30)
- "Но вообще как-то читал статью, что мод 1 предпочтительнее с точки зрения психомоторики, особенно на этапе обучения. Как мне кажется мод1 придумали планеристы, чтобы удобнее было модель с рук запускать.". [Надо листать комменты вниз](https://rcopen.com/forum/f4/topic40414/30)

Делаю выводы, что мода 1 для самолётов и для моделей, которые не FPV

P.S. [Бонус - сайт с красивой картинкой модов](https://rcsearch.ru/wiki/%D0%9C%D0%BE%D0%B4%D0%B0_%D0%B0%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%83%D1%80%D1%8B)
