### ISSUE TITLE
Elrs поддерживает частоту до 1000Hz

### ISSUE THREAD

**Issue by KondratokGK** [ikherty/droneDOCS#45]
Ошибка на сайте: [тык](https://propwashservice.ru/intro/tx.html#%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB%D1%8B-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)
Документация elrs: [бац](https://www.expresslrs.org/software/switch-config/?h=modes#summary-of-switch-configuration-modes)

**Comment by ikherty** [comment]
Обновлено, спасибо
