### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Suput** [ikherty/droneDOCS#9]
Добавить [`favicon`](https://ru.wikipedia.org/wiki/Favicon). С ней приятнее

![image](https://user-images.githubusercontent.com/40500378/203343214-b5fbc336-57c2-4b42-a19a-0cab9405eaac.png)

Update:
Бесплатные иконки можно поискать тут:
1. [По поиску `dron`](https://www.iconfinder.com/search?q=dron&price=free). При просмотре убедитесь, что включен фильтр `free` (бесплатные)
2. [Тоже сайт по поиску иконок](https://www.flaticon.com/search?word=drone&order_by=4). Какие могут быть платные - надо выбирать

**Comment by ikherty** [comment]
Fixed https://github.com/ikherty/droneDOCS/commit/cf9d9f35fc5b15f4437ec48f8c524789df45459b , спасибо за внимательность
